apiVersion: v1
kind: Pod
metadata:
  name: mypods
  labels:
    run: mypods
spec:
  containers:
    - image: 68017237/new-app:latest
      name: nodeimage1
      imagePullPolicy: Always
      ports:
        - containerPort: 3001
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  

