apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
    - image: 68017237/image1:latest
      name: nodeimage1
      imagePullPolicy: Always
      ports:
        - containerPort: 3001
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  

